// Code generated by "stringer -type=GoDBErrorCode"; DO NOT EDIT.

package godb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TupleNotFoundError-0]
	_ = x[PageFullError-1]
	_ = x[IncompatibleTypesError-2]
	_ = x[TypeMismatchError-3]
	_ = x[MalformedDataError-4]
	_ = x[BufferPoolFullError-5]
	_ = x[ParseError-6]
	_ = x[DuplicateTableError-7]
	_ = x[NoSuchTableError-8]
	_ = x[AmbiguousNameError-9]
	_ = x[IllegalOperationError-10]
	_ = x[DeadlockError-11]
	_ = x[IllegalTransactionError-12]
}

const _GoDBErrorCode_name = "TupleNotFoundErrorPageFullErrorIncompatibleTypesErrorTypeMismatchErrorMalformedDataErrorBufferPoolFullErrorParseErrorDuplicateTableErrorNoSuchTableErrorAmbiguousNameErrorIllegalOperationErrorDeadlockErrorIllegalTransactionError"

var _GoDBErrorCode_index = [...]uint8{0, 18, 31, 53, 70, 88, 107, 117, 136, 152, 170, 191, 204, 227}

func (i GoDBErrorCode) String() string {
	if i < 0 || i >= GoDBErrorCode(len(_GoDBErrorCode_index)-1) {
		return "GoDBErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GoDBErrorCode_name[_GoDBErrorCode_index[i]:_GoDBErrorCode_index[i+1]]
}
